import {
  JunkCategory,
  StorageBucket,
  LargeFile,
  DuplicateGroup,
  InstalledApp,
  PhotoItem,
  SystemMetrics,
  PermissionStatus,
} from '../types/cleaner';

export const INITIAL_JUNK_CATEGORIES: JunkCategory[] = [
  {
    id: 'cache',
    title: 'Hidden & Visible App Cache',
    category: 'cache',
    sizeBytes: 1684200000, // ~1.56 GB
    fileCount: 3412,
    description: 'Temporary cached data from streaming, social, and web apps. Safe to clear.',
    selected: true,
    requiresAndroid16Overlay: true,
    items: [
      {
        id: 'c-yt',
        name: 'YouTube Video Cache',
        path: '/data/user/0/com.google.android.youtube/cache',
        sizeBytes: 642000000,
        packageName: 'com.google.android.youtube',
        selected: true,
        details: 'ExoPlayer video fragments and thumbnail buffers',
      },
      {
        id: 'c-spot',
        name: 'Spotify Stream Buffers',
        path: '/data/user/0/com.spotify.music/cache',
        sizeBytes: 420500000,
        packageName: 'com.spotify.music',
        selected: true,
        details: 'Transient song audio cache (offline downloads kept safe)',
      },
      {
        id: 'c-ig',
        name: 'Instagram Reel Preloads',
        path: '/data/user/0/com.instagram.android/cache',
        sizeBytes: 318000000,
        packageName: 'com.instagram.android',
        selected: true,
        details: 'Fresco image cache & preloaded feed videos',
      },
      {
        id: 'c-rd',
        name: 'Reddit Media Buffer',
        path: '/data/user/0/com.reddit.frontpage/cache',
        sizeBytes: 195700000,
        packageName: 'com.reddit.frontpage',
        selected: true,
        details: 'Rendered post previews & GIF buffers',
      },
      {
        id: 'c-tk',
        name: 'TikTok Video Segments',
        path: '/data/user/0/com.zhiliaoapp.musically/cache',
        sizeBytes: 108000000,
        packageName: 'com.zhiliaoapp.musically',
        selected: true,
        details: 'HLS segment fragments and effect cache',
      },
    ],
  },
  {
    id: 'residual',
    title: 'Residual & Leftover Files',
    category: 'residual',
    sizeBytes: 524000000, // ~500 MB
    fileCount: 428,
    description: 'Orphaned folders and configuration left behind by uninstalled apps.',
    selected: true,
    items: [
      {
        id: 'res-1',
        name: 'Orphaned Apex Legends Data',
        path: '/sdcard/Android/data/com.ea.gp.apexlegendsmobile',
        sizeBytes: 382000000,
        selected: true,
        details: 'Uninstalled game texture packs & shader cache left behind',
      },
      {
        id: 'res-2',
        name: 'Leftover Canva Font Cache',
        path: '/sdcard/Android/media/com.canva.editor/.tmp_fonts',
        sizeBytes: 89000000,
        selected: true,
        details: 'Uninstalled app font assets',
      },
      {
        id: 'res-3',
        name: 'Old Deliveroo Location Cache',
        path: '/sdcard/Android/data/com.deliveroo.order/geocache',
        sizeBytes: 53000000,
        selected: true,
        details: 'Map tile remnants from uninstalled delivery app',
      },
    ],
  },
  {
    id: 'empty_folders',
    title: 'Empty Directories',
    category: 'empty_folders',
    sizeBytes: 0,
    fileCount: 76,
    description: 'Zero-byte orphaned folder structures cluttering file managers.',
    selected: true,
    items: [
      {
        id: 'ef-1',
        name: 'Empty Download subdirectories',
        path: '/sdcard/Download/.trash_null/',
        sizeBytes: 0,
        selected: true,
        details: '28 empty sub-folders',
      },
      {
        id: 'ef-2',
        name: 'DCIM gallery empty sync tokens',
        path: '/sdcard/DCIM/.empty_markers/',
        sizeBytes: 0,
        selected: true,
        details: '34 empty sub-folders',
      },
      {
        id: 'ef-3',
        name: 'Bluetooth temporary folders',
        path: '/sdcard/bluetooth/.incoming_pending/',
        sizeBytes: 0,
        selected: true,
        details: '14 empty sub-folders',
      },
    ],
  },
  {
    id: 'temp_logs',
    title: 'Temp Files, Thumbnails & Logs',
    category: 'temp_logs',
    sizeBytes: 412000000, // ~392 MB
    fileCount: 1850,
    description: 'System logcat dumps, tombstone reports, and stale gallery thumbnail files.',
    selected: true,
    items: [
      {
        id: 'tl-1',
        name: '.thumbnails cache file',
        path: '/sdcard/DCIM/.thumbnails/.thumbdata4--1967290299',
        sizeBytes: 289000000,
        selected: true,
        details: 'Corrupted legacy gallery index; rebuilds cleanly when needed',
      },
      {
        id: 'tl-2',
        name: 'Android crash log dumps',
        path: '/sdcard/Android/data/logs/dropbox/',
        sizeBytes: 81000000,
        selected: true,
        details: 'Stack traces and ANR traces older than 14 days',
      },
      {
        id: 'tl-3',
        name: 'Stale APK installation chunks',
        path: '/sdcard/Download/.package_cache/',
        sizeBytes: 42000000,
        selected: true,
        details: 'Failed/partial package installer temp files',
      },
    ],
  },
  {
    id: 'downloads',
    title: 'Old Downloads (>30 Days)',
    category: 'downloads',
    sizeBytes: 310000000, // ~295 MB
    fileCount: 19,
    description: 'Downloaded PDFs, APKs, and media unaccessed for over 30 days.',
    selected: false, // unselected by default for safety
    isSensitive: true,
    items: [
      {
        id: 'dl-1',
        name: 'boarding_pass_frankfurt_2025.pdf',
        path: '/sdcard/Download/boarding_pass_frankfurt_2025.pdf',
        sizeBytes: 4200000,
        selected: false,
        details: 'Downloaded 84 days ago',
      },
      {
        id: 'dl-2',
        name: 'Termux_v0.118_arch64.apk',
        path: '/sdcard/Download/Termux_v0.118_arch64.apk',
        sizeBytes: 98000000,
        selected: false,
        details: 'Already installed; installer file remaining in downloads',
      },
      {
        id: 'dl-3',
        name: 'annual_utility_report_2025.zip',
        path: '/sdcard/Download/annual_utility_report_2025.zip',
        sizeBytes: 207800000,
        selected: false,
        details: 'Downloaded 120 days ago',
      },
    ],
  },
  {
    id: 'clipboard',
    title: 'Clipboard History',
    category: 'clipboard',
    sizeBytes: 12400,
    fileCount: 8,
    description: 'Copied snippets, text buffers, and potential sensitive tokens in RAM/clip.',
    selected: true,
    items: [
      {
        id: 'clip-1',
        name: 'Authentication token snippet',
        path: 'SystemClipboard#primary',
        sizeBytes: 4200,
        selected: true,
        details: 'ghp_92x... (Sensitive developer token copied 2 hours ago)',
      },
      {
        id: 'clip-2',
        name: 'Copied street address',
        path: 'SystemClipboard#history_1',
        sizeBytes: 3100,
        selected: true,
        details: '742 Evergreen Terrace, Springfield',
      },
      {
        id: 'clip-3',
        name: 'Tracking URL with UTM tags',
        path: 'SystemClipboard#history_2',
        sizeBytes: 5100,
        selected: true,
        details: 'https://store.example.com/?ref=tracker&utm_source=ad',
      },
    ],
  },
  {
    id: 'browser',
    title: 'Browser Traces & Offline Storage',
    category: 'browser',
    sizeBytes: 215000000, // ~205 MB
    fileCount: 840,
    description: 'Web cache, favicon tables, and stale session tokens for enabled browsers.',
    selected: true,
    items: [
      {
        id: 'br-1',
        name: 'Chrome Web Cache',
        path: '/data/user/0/com.android.chrome/app_tabs/cache',
        sizeBytes: 142000000,
        packageName: 'com.android.chrome',
        selected: true,
        details: 'HTTP cached scripts and stylesheets (passwords untouched)',
      },
      {
        id: 'br-2',
        name: 'Firefox Media Storage',
        path: '/data/user/0/org.mozilla.firefox/files/mozilla/cache2',
        sizeBytes: 58000000,
        packageName: 'org.mozilla.firefox',
        selected: true,
        details: 'IndexedDB transient offline data',
      },
      {
        id: 'br-3',
        name: 'DuckDuckGo Favicon Database',
        path: '/data/user/0/com.duckduckgo.mobile.android/databases',
        sizeBytes: 15000000,
        packageName: 'com.duckduckgo.mobile.android',
        selected: true,
        details: 'Cached site icons & tracker blocking stats',
      },
    ],
  },
];

export const INITIAL_STORAGE_BUCKETS: StorageBucket[] = [
  {
    id: 'apps',
    label: 'Apps & Game Data',
    sizeBytes: 48500000000, // 48.5 GB
    color: '#00FF41',
    iconName: 'Smartphone',
    fileCount: 142,
    percentage: 38,
  },
  {
    id: 'photos',
    label: 'Photos & Images',
    sizeBytes: 28400000000, // 28.4 GB
    color: '#3b82f6',
    iconName: 'Image',
    fileCount: 6840,
    percentage: 22,
  },
  {
    id: 'videos',
    label: 'Videos',
    sizeBytes: 21200000000, // 21.2 GB
    color: '#a855f7',
    iconName: 'Film',
    fileCount: 124,
    percentage: 17,
  },
  {
    id: 'system',
    label: 'System (OS & Firmware)',
    sizeBytes: 15400000000, // 15.4 GB
    color: '#64748b',
    iconName: 'Cpu',
    fileCount: 1,
    percentage: 12,
  },
  {
    id: 'audio',
    label: 'Audio & Music',
    sizeBytes: 6200000000, // 6.2 GB
    color: '#f59e0b',
    iconName: 'Music',
    fileCount: 420,
    percentage: 5,
  },
  {
    id: 'documents',
    label: 'Documents',
    sizeBytes: 3800000000, // 3.8 GB
    color: '#06b6d4',
    iconName: 'FileText',
    fileCount: 890,
    percentage: 3,
  },
  {
    id: 'downloads',
    label: 'Downloads & Archives',
    sizeBytes: 2900000000, // 2.9 GB
    color: '#ec4899',
    iconName: 'Download',
    fileCount: 64,
    percentage: 2,
  },
  {
    id: 'other',
    label: 'Other & Junk Files',
    sizeBytes: 1600000000, // 1.6 GB
    color: '#eab308',
    iconName: 'Trash2',
    fileCount: 1200,
    percentage: 1,
  },
];

export const INITIAL_LARGE_FILES: LargeFile[] = [
  {
    id: 'lf-1',
    name: 'VID_20260714_4K60FPS_CONCERT.mp4',
    path: '/sdcard/DCIM/Camera/VID_20260714_4K60FPS_CONCERT.mp4',
    sizeBytes: 4200000000, // 4.2 GB
    type: 'video',
    lastModified: '2026-07-14',
  },
  {
    id: 'lf-2',
    name: 'Ubuntu_ARM64_RootFS_v24.04.tar.gz',
    path: '/sdcard/Download/Ubuntu_ARM64_RootFS_v24.04.tar.gz',
    sizeBytes: 1850000000, // 1.85 GB
    type: 'archive',
    lastModified: '2026-08-20',
  },
  {
    id: 'lf-3',
    name: 'Genshin_Impact_VoicePack_JP.pck',
    path: '/sdcard/Android/data/com.miHoYo.GenshinImpact/files/Audio_JP.pck',
    sizeBytes: 1650000000, // 1.65 GB
    type: 'other',
    lastModified: '2026-09-02',
  },
  {
    id: 'lf-4',
    name: 'Screen_Recording_20260905_1080p.mp4',
    path: '/sdcard/Movies/Screen_Recording_20260905_1080p.mp4',
    sizeBytes: 1100000000, // 1.1 GB
    type: 'video',
    lastModified: '2026-09-05',
  },
  {
    id: 'lf-5',
    name: 'Cyberpunk_Modpack_TextureHD.zip',
    path: '/sdcard/Download/Cyberpunk_Modpack_TextureHD.zip',
    sizeBytes: 890000000, // 890 MB
    type: 'archive',
    lastModified: '2026-08-11',
  },
  {
    id: 'lf-6',
    name: 'Podcast_Episodes_Batch_FLAC.zip',
    path: '/sdcard/Music/Podcasts/Batch_FLAC.zip',
    sizeBytes: 670000000, // 670 MB
    type: 'audio',
    lastModified: '2026-09-12',
  },
];

export const INITIAL_DUPLICATES: DuplicateGroup[] = [
  {
    hash: 'sha256-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    fileSize: 18500000, // 18.5 MB
    files: [
      {
        id: 'dup-1a',
        name: 'IMG_20260815_142055.jpg',
        path: '/sdcard/DCIM/Camera/IMG_20260815_142055.jpg',
        lastModified: '2026-08-15 14:20',
        selected: false,
        isPrimary: true,
      },
      {
        id: 'dup-1b',
        name: 'IMG_20260815_142055_copy.jpg',
        path: '/sdcard/Pictures/Telegram/IMG_20260815_142055_copy.jpg',
        lastModified: '2026-08-15 15:40',
        selected: true,
      },
      {
        id: 'dup-1c',
        name: 'shared_IMG_20260815.jpg',
        path: '/sdcard/Download/shared_IMG_20260815.jpg',
        lastModified: '2026-08-16 09:12',
        selected: true,
      },
    ],
  },
  {
    hash: 'sha256-8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
    fileSize: 42000000, // 42 MB
    files: [
      {
        id: 'dup-2a',
        name: 'Annual_Tax_Return_2025_Final.pdf',
        path: '/sdcard/Documents/Taxes/Annual_Tax_Return_2025_Final.pdf',
        lastModified: '2026-04-10',
        selected: false,
        isPrimary: true,
      },
      {
        id: 'dup-2b',
        name: 'Annual_Tax_Return_2025_Final (1).pdf',
        path: '/sdcard/Download/Annual_Tax_Return_2025_Final (1).pdf',
        lastModified: '2026-04-12',
        selected: true,
      },
    ],
  },
  {
    hash: 'sha256-a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
    fileSize: 12500000, // 12.5 MB
    files: [
      {
        id: 'dup-3a',
        name: 'Synthwave_Mix_04.mp3',
        path: '/sdcard/Music/Synthwave/Synthwave_Mix_04.mp3',
        lastModified: '2026-06-01',
        selected: false,
        isPrimary: true,
      },
      {
        id: 'dup-3b',
        name: 'track_04_download.mp3',
        path: '/sdcard/Download/track_04_download.mp3',
        lastModified: '2026-06-02',
        selected: true,
      },
    ],
  },
];

export const INITIAL_INSTALLED_APPS: InstalledApp[] = [
  {
    packageName: 'com.spotify.music',
    appName: 'Spotify Music',
    versionName: '8.9.72',
    appSizeBytes: 185000000,
    cacheSizeBytes: 420500000,
    dataSizeBytes: 1450000000,
    lastUsedDaysAgo: 0, // today
    dataUsedMonthlyMB: 4820,
    batteryDrainImpact: 'High',
    isHibernated: false,
    isSystemApp: false,
    iconBg: '#1DB954',
    iconInitial: 'S',
  },
  {
    packageName: 'com.instagram.android',
    appName: 'Instagram',
    versionName: '342.0.0',
    appSizeBytes: 210000000,
    cacheSizeBytes: 318000000,
    dataSizeBytes: 890000000,
    lastUsedDaysAgo: 1,
    dataUsedMonthlyMB: 8400,
    batteryDrainImpact: 'High',
    isHibernated: false,
    isSystemApp: false,
    iconBg: '#E1306C',
    iconInitial: 'I',
  },
  {
    packageName: 'com.zhiliaoapp.musically',
    appName: 'TikTok',
    versionName: '35.4.1',
    appSizeBytes: 245000000,
    cacheSizeBytes: 108000000,
    dataSizeBytes: 620000000,
    lastUsedDaysAgo: 2,
    dataUsedMonthlyMB: 12400,
    batteryDrainImpact: 'High',
    isHibernated: false,
    isSystemApp: false,
    iconBg: '#000000',
    iconInitial: 'T',
  },
  {
    packageName: 'com.duolingo',
    appName: 'Duolingo: Language Lessons',
    versionName: '6.12.0',
    appSizeBytes: 142000000,
    cacheSizeBytes: 45000000,
    dataSizeBytes: 180000000,
    lastUsedDaysAgo: 38, // unused > 30 days
    dataUsedMonthlyMB: 240,
    batteryDrainImpact: 'Moderate',
    isHibernated: false,
    isSystemApp: false,
    iconBg: '#58CC02',
    iconInitial: 'D',
  },
  {
    packageName: 'com.airbnb.android',
    appName: 'Airbnb',
    versionName: '24.28.1',
    appSizeBytes: 165000000,
    cacheSizeBytes: 62000000,
    dataSizeBytes: 95000000,
    lastUsedDaysAgo: 74, // unused > 60 days
    dataUsedMonthlyMB: 45,
    batteryDrainImpact: 'Low',
    isHibernated: true,
    isSystemApp: false,
    iconBg: '#FF5A5F',
    iconInitial: 'A',
  },
  {
    packageName: 'com.ubercab',
    appName: 'Uber: Request a Ride',
    versionName: '4.512.1',
    appSizeBytes: 130000000,
    cacheSizeBytes: 38000000,
    dataSizeBytes: 112000000,
    lastUsedDaysAgo: 98, // unused > 90 days
    dataUsedMonthlyMB: 12,
    batteryDrainImpact: 'Low',
    isHibernated: true,
    isSystemApp: false,
    iconBg: '#000000',
    iconInitial: 'U',
  },
  {
    packageName: 'org.videolan.vlc',
    appName: 'VLC for Android',
    versionName: '3.6.1',
    appSizeBytes: 95000000,
    cacheSizeBytes: 18000000,
    dataSizeBytes: 42000000,
    lastUsedDaysAgo: 6,
    dataUsedMonthlyMB: 0,
    batteryDrainImpact: 'Low',
    isHibernated: false,
    isSystemApp: false,
    iconBg: '#FF8800',
    iconInitial: 'V',
  },
  {
    packageName: 'com.adobe.reader',
    appName: 'Adobe Acrobat Reader',
    versionName: '24.7.1',
    appSizeBytes: 180000000,
    cacheSizeBytes: 54000000,
    dataSizeBytes: 320000000,
    lastUsedDaysAgo: 65, // unused > 60 days
    dataUsedMonthlyMB: 80,
    batteryDrainImpact: 'Low',
    isHibernated: false,
    isSystemApp: false,
    iconBg: '#ED2224',
    iconInitial: 'R',
  },
];

export const INITIAL_PHOTOS: PhotoItem[] = [
  {
    id: 'ph-1',
    name: 'IMG_20260912_174022.jpg',
    category: 'similar',
    originalSizeBytes: 4800000, // 4.8 MB
    width: 4032,
    height: 3024,
    dateTaken: '2026-09-12',
    isWhatsAppOrChat: false,
    previewUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
    selected: true,
    similarityGroupId: 'sim-sunset-1',
    issueDescription: '94% similarity with 3 other burst shots taken within 2 seconds',
  },
  {
    id: 'ph-2',
    name: 'IMG_20260912_174023.jpg',
    category: 'similar',
    originalSizeBytes: 4900000,
    width: 4032,
    height: 3024,
    dateTaken: '2026-09-12',
    isWhatsAppOrChat: false,
    previewUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
    selected: false,
    similarityGroupId: 'sim-sunset-1',
    issueDescription: 'Best photo kept as master reference',
  },
  {
    id: 'ph-3',
    name: 'IMG_20260908_231512.jpg',
    category: 'blurry',
    originalSizeBytes: 5200000,
    width: 4032,
    height: 3024,
    dateTaken: '2026-09-08',
    isWhatsAppOrChat: false,
    previewUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&auto=format&fit=crop&q=30',
    selected: true,
    issueDescription: 'High motion blur detected (Laplacian edge variance < 42)',
  },
  {
    id: 'ph-4',
    name: 'IMG_20260829_210401.jpg',
    category: 'dark',
    originalSizeBytes: 6100000,
    width: 4032,
    height: 3024,
    dateTaken: '2026-08-29',
    isWhatsAppOrChat: false,
    previewUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600&auto=format&fit=crop&q=40',
    selected: true,
    issueDescription: 'Underexposed (92% luminance histogram in shadows 0-15)',
  },
  {
    id: 'ph-5',
    name: 'Screenshot_20260510-142211.png',
    category: 'old_screenshot',
    originalSizeBytes: 3400000,
    width: 1080,
    height: 2400,
    dateTaken: '2026-05-10',
    isWhatsAppOrChat: false,
    previewUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    selected: true,
    issueDescription: 'Screenshot older than 120 days. Never opened since creation.',
  },
];

export const INITIAL_PERMISSIONS: PermissionStatus[] = [
  {
    id: 'storage_manage',
    name: 'All Files Storage Access',
    androidPermission: 'android.permission.MANAGE_EXTERNAL_STORAGE',
    rationale: 'Required to scan orphaned residual folders, large files, and duplicates outside media store.',
    granted: true,
    isCritical: true,
    category: 'storage',
  },
  {
    id: 'usage_stats',
    name: 'App Usage Statistics',
    androidPermission: 'android.permission.PACKAGE_USAGE_STATS',
    rationale: 'Enables identification of unused apps (30/60/90 days) and background battery drain diagnostics.',
    granted: true,
    isCritical: true,
    category: 'usage',
  },
  {
    id: 'post_notifications',
    name: 'Scan Notifications',
    androidPermission: 'android.permission.POST_NOTIFICATIONS',
    rationale: 'Allows WorkManager scheduled clean notifications and active purge completion reports.',
    granted: true,
    isCritical: false,
    category: 'notifications',
  },
  {
    id: 'accessibility_opt',
    name: 'Guided App Hibernation',
    androidPermission: 'android.permission.BIND_ACCESSIBILITY_SERVICE',
    rationale: 'Optional: Permits 1-tap automated closing of background battery-draining apps via system settings.',
    granted: false,
    isCritical: false,
    category: 'accessibility',
  },
  {
    id: 'call_log',
    name: 'Call History Clean',
    androidPermission: 'android.permission.READ_CALL_LOG & WRITE_CALL_LOG',
    rationale: 'Optional privacy tool to delete old spam or outgoing call traces.',
    granted: false,
    isCritical: false,
    category: 'privacy',
  },
  {
    id: 'sms',
    name: 'SMS Clean (OTPs / Promos)',
    androidPermission: 'android.permission.READ_SMS & WRITE_SMS',
    rationale: 'Optional privacy tool to purge expired 2FA OTP codes and marketing texts older than 7 days.',
    granted: false,
    isCritical: false,
    category: 'privacy',
  },
];
